FROM registry.access.redhat.com/ubi9/python-312:latest

USER 0
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/todo_backend/

USER 1001
EXPOSE 8000
CMD ["uvicorn", "todo_backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
