apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  namespace: demo-todo
type: Opaque
stringData:
  PG_HOST: postgres.demo-db.svc.cluster.local
  PG_PORT: "5432"
  PG_DB: todos
  PG_USER: todo
  PG_PASSWORD: clrhsi-demo-2026
