apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-frontend
  namespace: demo-frontend
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ingress-gateway
  to:
    - group: ""
      kind: Service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-todo
  namespace: demo-todo
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ingress-gateway
  to:
    - group: ""
      kind: Service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-weather
  namespace: demo-weather
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ingress-gateway
  to:
    - group: ""
      kind: Service
