apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: demo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1.27-alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: static
              mountPath: /usr/share/nginx/html
          readinessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 5
      volumes:
        - name: static
          configMap:
            name: frontend-static
