apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: demo-db
type: Opaque
stringData:
  POSTGRESQL_USER: todo
  POSTGRESQL_PASSWORD: clrhsi-demo-2026
  POSTGRESQL_DATABASE: todos
