apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: weather-ratelimit
  namespace: demo-weather
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: weather-route
  limits:
    per-route:
      rates:
        - limit: 10
          window: 1m
      when:
        - predicate: "request.method != 'OPTIONS'"
      counters:
        - expression: request.host
